### ISSUE TITLE
PETSc/Cython not working when not installed from source

### ISSUE THREAD

**Issue by jorgensd** [scientificcomputing/packages#10]
See:
https://gitlab.com/petsc/petsc/-/issues/1359
https://github.com/cython/cython/pull/5383
We need to wait for a new `Cython` release (0.29.x) to make the current workflow in the Dockerfile work.
Temporary pin of `Cython` is proposed in: https://github.com/FEniCS/dolfinx/pull/2620/files

**Comment by finsberg** [comment]
So we need to add a 
```
python3 -m pip install Cython==0.29.32
```
before this line https://github.com/scientificcomputing/packages/blob/0a405fa3f60802a2f6497baf5a19b1cc4908d668/fenics/Dockerfile#L134, right?

**Comment by jorgensd** [comment]
> So we need to add a
> 
> ```
> python3 -m pip install Cython==0.29.32
> ```
> 
> before this line
> 
> https://github.com/scientificcomputing/packages/blob/0a405fa3f60802a2f6497baf5a19b1cc4908d668/fenics/Dockerfile#L134
> , right?

Yes. I just didnt have time before calling it a day tomorrow to add it.

**Comment by finsberg** [comment]
@jorgensd I guess this issue was fixed in https://github.com/scientificcomputing/packages/pull/11 ?
