### ISSUE TITLE
UFL changed repository

### ISSUE THREAD

**Issue by Reidmen** [scientificcomputing/packages#18]
The `fenics/Dockerfile` appears to be broken since UFL legacy is now in this repository [ufl-legacy](https://github.com/FEniCS/ufl-legacy). 

The issue was encountered while trying to generate an openmpi version of the latest legacy fenics.

I'll create a pull request.

**Comment by finsberg** [comment]
Fixed in https://github.com/scientificcomputing/packages/pull/19
Also built a new docker image here: https://github.com/scientificcomputing/packages/pkgs/container/fenics/147933141?tag=2023-11-15
